version: "3"

services:
  crm_frontend_vite_client:
    container_name: crm_frontend_vite_client
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    restart: no
    working_dir: /app
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
      - "5173:5173"
    env_file: ".env"
    volumes:
      - ./:/app
      - /app/node_modules
